name: donations
description: A very good dart package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  meta: ^1.7.0
  uuid: ^3.0.0
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  get: ^4.6.6
  build_runner: ^2.4.15
  build_runner_core: ^8.0.0

dev_dependencies:
  json_serializable: ^6.3.1
  mocktail: ^1.0.4
  test: 1.25.8
  very_good_analysis: ^6.0.0
